#   Copyright (c) 2016, 2022, XDBTIME Taras Guliak 
#   All rights reserved.

def performance(session):

    print('')
    print('XDBTIME reports for MySQL')
    print('Copyright (c) 2016, 2022, XDBTIME Taras Guliak')
    print('Version: 2022.11')
    print('')
    print('Creating MySQL Performance Summary Report ...') 
    
    #events_statements_summary_global_by_event_name
    stmt_statements = ("SELECT CONCAT('+ \"',wait_class,',',wait_event,',',tr_wait_time_seconds,',',tr_wait_time_seconds,'\\n\"') as x "
                       "FROM (SELECT SUBSTRING(s.event_name,LOCATE('/',s.event_name,1)+1,LOCATE('/',s.event_name,LOCATE('/',s.event_name,1)+1)- LOCATE('/',s.event_name,1)-1) wait_class, SUBSTRING(s.event_name,LOCATE('/',s.event_name,LOCATE('/',s.event_name,1)+1)+1,LENGTH(s.event_name) - LOCATE('/',s.event_name,LOCATE('/',s.event_name,1)+1)) wait_event, ROUND(tr_timer_wait/1000000000000,0) tr_wait_time_seconds "
                       "FROM (SELECT event_name, sum_timer_wait tr_timer_wait FROM performance_schema.events_statements_summary_global_by_event_name WHERE event_name!='wait/synch/cond/sql/COND_queue_state' ORDER BY sum_timer_wait DESC LIMIT 15) s WHERE (ROUND(tr_timer_wait/100,0))>0) b; ")

    #events_waits_summary_global_by_event_name
    stmt_waits =   ("SELECT CONCAT('+ \"',wait_class,',',wait_event,',',tr_wait_time_seconds,',',tr_wait_time_seconds,'\\n\"') as x "
                    "FROM (SELECT SUBSTRING(s.event_name,LOCATE('/',s.event_name,1)+1, IF(LOCATE('/',s.event_name,LOCATE('/',s.event_name,LOCATE('/',s.event_name,1)+1)+1) = 0,LENGTH(s.event_name),LOCATE('/',s.event_name,LOCATE('/',s.event_name,LOCATE('/',s.event_name,1)+1)+1)) - LOCATE('/',s.event_name,1)-1) wait_class, SUBSTRING(s.event_name,LOCATE('/',s.event_name,LOCATE('/',s.event_name,LOCATE('/',s.event_name,1)+1)+1)+1, LENGTH(s.event_name) - LOCATE('/',s.event_name,LOCATE('/',s.event_name,LOCATE('/',s.event_name,1)+1)+1)) wait_event, ROUND(tr_timer_wait/1000000000000,0) tr_wait_time_seconds "
                    "FROM (SELECT event_name, sum_timer_wait tr_timer_wait FROM performance_schema.events_waits_summary_global_by_event_name WHERE event_name!='wait/synch/cond/sql/COND_queue_state' ORDER BY sum_timer_wait DESC LIMIT 15) s "
                    "WHERE event_name!='idle' and (ROUND(tr_timer_wait/1000000000000,0))>0) b; ")

    #events_stages_summary_global_by_event_name
    stmt_stages =  ("SELECT CONCAT('+ \"',wait_class,',',wait_event,',',tr_wait_time_seconds,',',tr_wait_time_seconds,'\\n\"') as x "
                    "FROM (SELECT SUBSTRING(s.event_name,LOCATE('/',s.event_name,1)+1,LOCATE('/',s.event_name,LOCATE('/',s.event_name,1)+1)- LOCATE('/',s.event_name,1)-1) wait_class, SUBSTRING(s.event_name,LOCATE('/',s.event_name,LOCATE('/',s.event_name,1)+1)+1,LENGTH(s.event_name) - LOCATE('/',s.event_name,LOCATE('/',s.event_name,1)+1)) wait_event, ROUND(tr_timer_wait/1000000000000,0) tr_wait_time_seconds "
                    "FROM (SELECT event_name, sum_timer_wait tr_timer_wait FROM performance_schema.events_stages_summary_global_by_event_name WHERE event_name!='wait/synch/cond/sql/COND_queue_state' ORDER BY sum_timer_wait DESC LIMIT 15 ) s "
                    "WHERE (ROUND(tr_timer_wait/1000000000000,0))>0) b; ")
    #csvSqlStatsChartMySQL

    stmt_digest_charts =   ("SELECT ANY_VALUE(CONCAT('+ \"','SQL_TYPE,',IFNULL(b.SCHEMA_NAME,'other'),',',COUNT(1),',',COUNT(1),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','ERRORS,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_ERRORS,0)),',',SUM(IFNULL(SUM_ERRORS,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','WARNINGS,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_WARNINGS,0)),',',SUM(IFNULL(SUM_WARNINGS,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','ROWS_AFFECTED,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_ROWS_AFFECTED,0)),',',SUM(IFNULL(SUM_ROWS_AFFECTED,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','ROWS_SENT,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_ROWS_SENT,0)),',',SUM(IFNULL(SUM_ROWS_SENT,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','ROWS_EXAMINED,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_ROWS_EXAMINED,0)),',',SUM(IFNULL(SUM_ROWS_EXAMINED,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','EXECUTIONS,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(COUNT_STAR,0)),',',SUM(IFNULL(COUNT_STAR,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','CREATED_TMP_DISK_TABLES,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_CREATED_TMP_DISK_TABLES,0)),',',SUM(IFNULL(SUM_CREATED_TMP_DISK_TABLES,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','CREATED_TMP_TABLES,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_CREATED_TMP_TABLES,0)),',',SUM(IFNULL(SUM_CREATED_TMP_TABLES,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','SELECT_FULL_JOIN,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_SELECT_FULL_JOIN,0)),',',SUM(IFNULL(SUM_SELECT_FULL_JOIN,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','SELECT_FULL_RANGE_JOIN,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_SELECT_FULL_RANGE_JOIN,0)),',',SUM(IFNULL(SUM_SELECT_FULL_RANGE_JOIN,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','SELECT_RANGE,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_SELECT_RANGE,0)),',',SUM(IFNULL(SUM_SELECT_RANGE,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','SELECT_RANGE_CHECK,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_SELECT_RANGE_CHECK,0)),',',SUM(IFNULL(SUM_SELECT_RANGE_CHECK,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','SELECT_SCAN,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_SELECT_SCAN,0)),',',SUM(IFNULL(SUM_SELECT_SCAN,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','SORT_MERGE_PASSES,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_SORT_MERGE_PASSES,0)),',',SUM(IFNULL(SUM_SORT_MERGE_PASSES,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','SORT_RANGE,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_SORT_RANGE,0)),',',SUM(IFNULL(SUM_SORT_RANGE,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','SORT_ROWS,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_SORT_ROWS,0)),',',SUM(IFNULL(SUM_SORT_ROWS,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','SORT_SCAN,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_SORT_SCAN,0)),',',SUM(IFNULL(SUM_SORT_SCAN,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','NO_INDEX_USED,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_NO_INDEX_USED,0)),',',SUM(IFNULL(SUM_NO_INDEX_USED,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','NO_GOOD_INDEX_USED,',IFNULL(b.SCHEMA_NAME,'other'),',',SUM(IFNULL(SUM_NO_GOOD_INDEX_USED,0)),',',SUM(IFNULL(SUM_NO_GOOD_INDEX_USED,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','TIMER_WAIT,',IFNULL(b.SCHEMA_NAME,'other'),',',(ROUND(SUM(IFNULL(SUM_TIMER_WAIT,0))/1000000000000,0)),',',(ROUND(SUM(IFNULL(SUM_TIMER_WAIT,0))/1000000000000,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other') UNION "
                            "SELECT ANY_VALUE(CONCAT('+ \"','LOCK_TIME,',IFNULL(b.SCHEMA_NAME,'other'),',',(ROUND(SUM(IFNULL(SUM_LOCK_TIME,0))/1000000000000,0)),',',(ROUND(SUM(IFNULL(SUM_LOCK_TIME,0))/1000000000000,0)),'\\n\"')) as x from performance_schema.events_statements_summary_by_digest a left join (select IFNULL(SCHEMA_NAME,'null') schema_name, sum(sum_timer_wait) from performance_schema.events_statements_summary_by_digest group by IFNULL(SCHEMA_NAME,'null') ORDER BY 2 DESC LIMIT 10) b ON IFNULL(a.SCHEMA_NAME,'null') = b.schema_name GROUP BY IFNULL(b.SCHEMA_NAME,'other');")
    #csvSqlStatsTableMySQL
    stmt_digest_tables =   ("SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_LOCK_TIME,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_LOCK_TIME>0 ORDER BY  SUM_LOCK_TIME DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_ERRORS,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_ERRORS>0 ORDER BY  SUM_ERRORS DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_WARNINGS,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_WARNINGS>0 ORDER BY  SUM_WARNINGS DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_ROWS_AFFECTED,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_ROWS_AFFECTED>0 ORDER BY  SUM_ROWS_AFFECTED DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_ROWS_SENT,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_ROWS_SENT>0 ORDER BY  SUM_ROWS_SENT DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_ROWS_EXAMINED,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_ROWS_EXAMINED>0 ORDER BY  SUM_ROWS_EXAMINED DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','COUNT_STAR,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where COUNT_STAR>0 ORDER BY  COUNT_STAR DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_CREATED_TMP_DISK_TABLES,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_CREATED_TMP_DISK_TABLES>0 ORDER BY  SUM_CREATED_TMP_DISK_TABLES DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_CREATED_TMP_TABLES,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_CREATED_TMP_TABLES>0 ORDER BY  SUM_CREATED_TMP_TABLES DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_SELECT_FULL_JOIN,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_SELECT_FULL_JOIN>0 ORDER BY  SUM_SELECT_FULL_JOIN DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_TIMER_WAIT,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_TIMER_WAIT>0 ORDER BY  SUM_TIMER_WAIT DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_SELECT_FULL_RANGE_JOIN,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_SELECT_FULL_RANGE_JOIN>0 ORDER BY  SUM_SELECT_FULL_RANGE_JOIN DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_SELECT_RANGE,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_SELECT_RANGE>0 ORDER BY  SUM_SELECT_RANGE DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_SELECT_RANGE_CHECK,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_SELECT_RANGE_CHECK>0 ORDER BY  SUM_SELECT_RANGE_CHECK DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_SELECT_SCAN,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_SELECT_SCAN>0 ORDER BY  SUM_SELECT_SCAN DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_SORT_MERGE_PASSES,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_SORT_MERGE_PASSES>0 ORDER BY  SUM_SORT_MERGE_PASSES DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_SORT_RANGE,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_SORT_RANGE>0 ORDER BY  SUM_SORT_RANGE DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_SORT_ROWS,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_SORT_ROWS>0 ORDER BY  SUM_SORT_ROWS DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_SORT_SCAN,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_SORT_SCAN>0 ORDER BY  SUM_SORT_SCAN DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_NO_INDEX_USED,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_NO_INDEX_USED>0 ORDER BY  SUM_NO_INDEX_USED DESC LIMIT 20) a UNION "
                            "SELECT a.col as x FROM (SELECT CONCAT('+ \"','SUM_NO_GOOD_INDEX_USED,',IFNULL(SCHEMA_NAME,'null'),',',DIGEST,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',ROUND(SUM_LOCK_TIME/1000000000000,0),',',SUM_ERRORS,',',SUM_WARNINGS,',',SUM_ROWS_AFFECTED,',',SUM_ROWS_SENT,',',SUM_ROWS_EXAMINED,',',SUM_CREATED_TMP_DISK_TABLES,',',SUM_CREATED_TMP_TABLES,',',SUM_SELECT_FULL_JOIN,',',SUM_SELECT_FULL_RANGE_JOIN,',',SUM_SELECT_RANGE,',',SUM_SELECT_RANGE_CHECK,',',SUM_SELECT_SCAN,',',SUM_SORT_MERGE_PASSES,',',SUM_SORT_RANGE,',',SUM_SORT_ROWS,',',SUM_SORT_SCAN,',',SUM_NO_INDEX_USED,',',SUM_NO_GOOD_INDEX_USED,'\\n\"') as col from performance_schema.events_statements_summary_by_digest x where SUM_NO_GOOD_INDEX_USED>0 ORDER BY  SUM_NO_GOOD_INDEX_USED DESC LIMIT 20) a ;")

    #csvFileSummaryByEventMySQL
    stmt_file_summary = ("SELECT CONCAT('+ \"',EVENT_NAME,',',COUNT_STAR,',',ROUND(SUM_TIMER_WAIT/1000000000000,0),',',ROUND(MIN_TIMER_WAIT/1000000000000,6),',',ROUND(AVG_TIMER_WAIT/1000000000000,6),',',ROUND(MAX_TIMER_WAIT/1000000000000,6),',',COUNT_READ,',',ROUND(SUM_TIMER_READ/1000000000000,0),',',ROUND(MIN_TIMER_READ/1000000000000,6),',',ROUND(AVG_TIMER_READ/1000000000000,6),',',ROUND(MAX_TIMER_READ/1000000000000,6),',',SUM_NUMBER_OF_BYTES_READ,',',COUNT_WRITE,',',ROUND(SUM_TIMER_WRITE/1000000000000,0),',',ROUND(MIN_TIMER_WRITE/1000000000000,6),',',ROUND(AVG_TIMER_WRITE/1000000000000,6),',',ROUND(MAX_TIMER_WRITE/1000000000000,6),',',SUM_NUMBER_OF_BYTES_WRITE,',',COUNT_MISC,',',ROUND(SUM_TIMER_MISC/1000000000000,0),',',ROUND(MIN_TIMER_MISC/1000000000000,6),',',ROUND(AVG_TIMER_MISC/1000000000000,6),',',ROUND(MAX_TIMER_MISC/1000000000000,6),'\\n\"') as x "
                        "FROM performance_schema.file_summary_by_event_name WHERE SUM_TIMER_WAIT>0 ORDER BY SUM_TIMER_WAIT DESC LIMIT 20;")
    #csvSQLText
    stmt_sql_text = ("SELECT CONCAT('+ \"',COALESCE(schema_name,' '),'!@#!',digest,'!@#!',SUBSTRING(DIGEST_TEXT,1,2000),'\\n\"') FROM performance_schema.events_statements_summary_by_digest;")

    #csvGlobalStatus
    stmt_global_status = ("SELECT CONCAT('+ \"',VARIABLE_NAME,',',VARIABLE_VALUE,'\\n\"') FROM performance_schema.global_status where variable_value REGEXP '^-?[0-9]+$';")

    #csvDBSummary
    stmt_db_summary = "SELECT CONCAT('+ \"',@@hostname,',',@@innodb_buffer_pool_size,',',@@version,',',@@version_comment,',',@@version_compile_os,',',@@version_compile_machine,',',TIME_FORMAT(SEC_TO_TIME(VARIABLE_VALUE ),'%Hh %im %ss'),',',DATE_FORMAT(SYSDATE(), '%d %b %Y %H:%i:%s'),'\\n\"') FROM performance_schema.global_status WHERE VARIABLE_NAME='Uptime';"

    stmt_file_name = "select CONCAT('./reports/mysql-xdbperf-status-',@@hostname,'-',DATE_FORMAT(SYSDATE(), '%Y-%m-%d-%H-%i-%s'),'.html');"
    result_file_name = session.run_sql(stmt_file_name)
    row = result_file_name.fetch_one()
    file_name = row[0]
    
    
    header = footer = ""

    with open('./templates/mysql-xdbperf-status-header.html') as fh:
        header = fh.read()

    with open('./templates/mysql-xdbperf-status-footer.html') as ff:
        footer = ff.read()    

    with open(file_name, 'w') as f:
        f.write(header)
        
        result_statements = session.run_sql(stmt_statements)
        f.write("%s\n" % "csvStatementsSummaryMySQL = csvStatementsSummaryMySQL")
        for row in result_statements.fetch_all():
            f.write("%s\n" % str(repr(row[0])[1:-1]))
        f.write("%s\n" % ";")
        result_waits = session.run_sql(stmt_waits)
        f.write("%s\n" % "csvWaitsSummaryMySQL = csvWaitsSummaryMySQL")    
        for row in result_waits.fetch_all():
            f.write("%s\n" % str(repr(row[0])[1:-1]))
        f.write("%s\n" % ";")
        result_stages = session.run_sql(stmt_stages)
        f.write("%s\n" % "csvStagesSummaryMySQL = csvStagesSummaryMySQL")    
        for row in result_stages.fetch_all():
            f.write("%s\n" % str(repr(row[0])[1:-1]))
        f.write("%s\n" % ";")
        result_digest_charts = session.run_sql(stmt_digest_charts)
        f.write("%s\n" % "csvSqlStatsChartMySQL = csvSqlStatsChartMySQL")    
        for row in result_digest_charts.fetch_all():
            f.write("%s\n" % str(repr(row[0])[1:-1]))
        f.write("%s\n" % ";")
        result_digest_tables = session.run_sql(stmt_digest_tables)
        f.write("%s\n" % "csvSqlStatsTableMySQL = csvSqlStatsTableMySQL")    
        for row in result_digest_tables.fetch_all():
            f.write("%s\n" % str(repr(row[0])[1:-1]))
        f.write("%s\n" % ";")
        result_file_summary = session.run_sql(stmt_file_summary)
        f.write("%s\n" % "csvFileSummaryByEventMySQL = csvFileSummaryByEventMySQL")    
        for row in result_file_summary.fetch_all():
            f.write("%s\n" % str(repr(row[0])[1:-1]))
        f.write("%s\n" % ";")
        result_db_summary = session.run_sql(stmt_db_summary)
        f.write("%s\n" % "csvDbSummary = csvDbSummary")    
        for row in result_db_summary.fetch_all():
            f.write("%s\n" % str(repr(row[0])[1:-1]))
        f.write("%s\n" % ";")
        result_sql_text = session.run_sql(stmt_sql_text)
        f.write("%s\n" % "csvSQLText = csvSQLText")    
        for row in result_sql_text.fetch_all():
            f.write("%s\n" % str(repr(row[0])[1:-1]))
        f.write("%s\n" % ";")
        result_global_status = session.run_sql(stmt_global_status)
        f.write("%s\n" % "csvGlobalStatus = csvGlobalStatus")    
        for row in result_global_status.fetch_all():
            f.write("%s\n" % str(repr(row[0])[1:-1]))
        f.write("%s\n" % ";")

        f.write(footer)    

    f.close()

    print('Report is written to: '+file_name)

    print('')

    return file_name

shell.register_report(
    'performance',
    'print',
    performance,
    {
        'brief': 'Generates Database Performance Summary Report for MySQL.',
        'details': ['You need the SELECT privilege on PERFORMANCE_SCHEMA schema. '
                    + 'Example: "\show performance" will generate performance report based on available data in Performance Schema. '],
        'argc': '0'
    }
)